### ISSUE TITLE
Initial test

### ISSUE THREAD

**Issue by dc1rdb** [pothosware/SoapyRTLSDR#1]
Did a quick check with three different dongles:

```
[DEBUG] Device #0: Generic RTL2832U OEM
[DEBUG]     Manufacturer: Realtek, Product Name: RTL2838UHIDIR, Serial: 00000153
Found Rafael Micro R820T tuner
[DEBUG]      Tuner type: Rafael Micro R820T
```

```
[DEBUG] Device #0: Terratec NOXON DAB/DAB+ USB dongle (rev 2)
[DEBUG]     Manufacturer: Realtek, Product Name: RTL2832U, Serial: 00000001
Found Elonics E4000 tuner
[DEBUG]      Tuner type: Elonics E4000
```

```
[DEBUG] Device #0: Terratec NOXON DAB/DAB+ USB dongle (rev 1)
[DEBUG]     Manufacturer: NOXON, Product Name: DAB Stick, Serial: 0
Found Fitipower FC0013 tuner
[DEBUG]      Tuner type: Fitipower FC0013
```

All three are working fine, but audio is a little bit choppy, independent of bandwidth setting.

**Comment by cjcliffe** [comment]
@dc1rdb nice, it should be mostly functional now; I'm going to use it to start implementing gain controllers through the SoapySDR gain interface soon.

Note that CubicSDR soapysdr-support branch has been updated too; there was a bug in device selection that was preventing it from actually switching between devices.
