### ISSUE TITLE
Implement new info query API calls

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapyRTLSDR#12]
Calls to implement:
- getFrequencyArgsInfo()
- getStreamFormats()
- getNativeStreamFormat()
- getStreamArgsInfo()
- Possibly settings API calls...

CMakeList version update:
- `find_package(SoapySDR "0.4.0" NO_MODULE)`

Related issue:
- https://github.com/pothosware/SoapySDR/issues/37

**Comment by cjcliffe** [comment]
Looking good so far; I have most of it implemented and building here.
