### ISSUE TITLE
Release tag for E4000 support

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapyRTLSDR#19]
@cjcliffe whats the state of the E4000 work? Im happy to tag things and spin off new binaries eventually.

**Comment by cjcliffe** [comment]
@guruofquality it appears to be working for me, but I'm going to do some more testing based on user reports

**Comment by guruofquality** [comment]
howabout now :-)

**Comment by cjcliffe** [comment]
Works for me and I haven't had any more reports of problems with it -- I think it's probably ready to go.

**Comment by guruofquality** [comment]
Cool. Done!
