### ISSUE TITLE
setupStream() mangles tunerGain

### ISSUE THREAD

**Issue by mutability** [pothosware/SoapyRTLSDR#51]
setupStream resets tunerGain by calling rtlsdr_get_tuner_gain, but that return value is in tenths of a dB and there is no conversion done, so future calls to getGain() return a value that is wrong by a factor of 10.

https://github.com/pothosware/SoapyRTLSDR/blob/bec4f0504b29369fd8ff651e6954b960991bc1b1/Streaming.cpp#L289

**Comment by zuckschwerdt** [comment]
Good catch! Fixed now.
