### ISSUE TITLE
Long pause every time frequency is changed

### ISSUE THREAD

**Issue by argilo** [pothosware/SoapyRTLSDR#52]
#49 has made SoapyRTLSDR unusable in Gqrx because reception is interrupted for approximately one second every time the frequency is adjusted.

@cjcliffe Can you let me know what the bug was that prompted #49? I'd be happy to help find a better solution for it.

**Comment by guruofquality** [comment]
This bug that caused this was reverted, it will be in the next tag: https://github.com/pothosware/SoapyRTLSDR/commit/60b41d51a983ae1e4a8f5e5fa8f6ea174363049c
