### ISSUE TITLE
Create release with getSampleRateRange

### ISSUE THREAD

**Issue by schneider42** [pothosware/SoapyRTLSDR#61]
Would be nice to have a release with https://github.com/pothosware/SoapyRTLSDR/commit/8277756a9ee4f87bce5b18deab39fe85abef22ce inside to get that into peoples hands. The last release was just a few days before that change.

**Comment by guruofquality** [comment]
sure thing!
https://github.com/pothosware/SoapyRTLSDR/tree/soapy-rtl-sdr-0.3.3
