### ISSUE TITLE
undefined reference to "__atomic_load_8

### ISSUE THREAD

**Issue by Marial128** [pothosware/SoapyRTLSDR#63]
So first sorry for my english (I'm french)
I'm trying to install librealsense on a raspberry PI 3 but when I'm buiding it's show this error :
~/Work/librealsense/build $ make -j1
[ 55%] Built target fw
[ 55%] Built target realsense-file
[ 55%] Built target realsense2
[ 55%] Built target libcurl
[ 55%] Built target glfw
[ 55%] Built target realsense2-gl
[ 55%] Linking CXX executable rs-hello-realsense
/usr/bin/ld : ../../librealsense2.so.2.50.0 : undefined reference to "__atomic_load_8".
/usr/bin/ld : ../../librealsense2.so.2.50.0 : undefined reference to "__atomic_store_8
/usr/bin/ld : ../../librealsense2.so.2.50.0 : undefined reference to "__atomic_fetch_add_8
collect2: error: ld returned 1 exit status
make[2]: *** [examples/hello-realsense/CMakeFiles/rs-hello-realsense.dir/build.make:110 : examples/hello-realsense/rs-hello-realsense] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:1240 : examples/hello-realsense/CMakeFiles/rs-hello-realsense.dir/all] Erreur 2
make: *** [Makefile:149 : all] Erreur 2

If anyone has an idea of what to do ?

**Comment by zuckschwerdt** [comment]
See maybe #40, #41, and #47. But you should raise the issue with the `librealsense` project, this here is about SoapyRTLSDR.
